import string

def get_password_strength(password):
    # Setup requirements
    special_chars = string.punctuation
    length = len(password)
    
    # Check conditions
    has_number = any(char.isdigit() for char in password)
    has_special = any(char in special_chars for char in password)
    has_upper = any(char.isupper() for char in password)
    
    # Logic for Strength Level
    if length < 12:
        return "Too Short", "❌ (Min. 12 characters required)" # a tuple it is generated by default
    
    # If it has both number AND special character (and length >= 12)
    elif has_number and has_special and has_upper:
        return "Strong", "🔥"
    
    # If it has at least one of them (and length >= 12)
    elif has_number or has_special or has_upper:
        return "Balanced", "⚖️"
    
    # If it's just a long string of letters
    else: 
        return "Weak", "☁️"

def play_game():
    print("--- 🛡️  Password Power Level 🛡️  ---")
    user_input = input("Enter a password to test: ")
    
    # !! unpacking of a tuple !!
    strength, emoji = get_password_strength(user_input)
    
    print("\n" + "="*30)
    print(f"Password: {user_input}")
    print(f"Length: {len(user_input)}")
    print(f"Strength Level: {strength} {emoji}")
    print("="*30)

# Run the game
if __name__ == "__main__":
    play_game()